### ISSUE TITLE
No hardware diagram or software structure

### ISSUE THREAD

**Issue by npes-95** [Fyfe93/GroPro#1]
Would be good to see how the hardware works (PCB schematic, datasheets, etc...) and have access to a general software flow block diagram. 

- Team 4

**Comment by TheAliRobertson** [comment]
Hi @npes-95 . Thanks for your feedback! We are working on resurrecting this issue and having the PCB schematics uploaded as soon as possible for audience perusal.

**Comment by obwarner1** [comment]
Hi @npes-95, I have now uploaded the schematics for the system. They include the library cache as well so you can open them straight away with KiCad. PCB files will be uploaded shortly.
