### ISSUE TITLE
Issues

### ISSUE THREAD

**Issue by alex-angelov** [Fyfe93/GroPro#2]
1) Power considerations - will the Pi (assuming you won't use a PSU) be able to supply enough power for the LEDs; 
2) More information about the expected latency between system components needed. Some RPi CPU benchmarks on parts of the code would be good to have.
Very good github project description, file (branch) management and history of commits.
-Team 11

**Comment by obwarner1** [comment]
@alex-angelov RE: power considerations, the LEDs, sensor and ICs will be powered from a separate PSU.
