### ISSUE TITLE
Software Improvements

### ISSUE THREAD

**Issue by 2077762b** [Fyfe93/GroPro#4]
This is a very interesting project. Here are a few issues to work on:
* There is minimal code at the moment. It would be great to see code that is added in the future make use of the object orientated nature of C++ and include appropriate commentary which explains the purpose of each function. 
* There are currently no PCB files. These would be interesting to see.
* Commit messages could be more meaningful. "Third commit" is not helpful. Ideally they should explain which files have been edited and why.

**Team 10**

**Comment by obwarner1** [comment]
Hi @2077762b, re:PCB files, they will be uploaded shortly. Thanks!

**Comment by obwarner1** [comment]
PCB Files now uploaded, cheers!

**Comment by Fyfe93** [comment]
Object Oriented style code has now been developed for high level control of our LED driver. More to come for sensor control. Thank you for the tip on commit messages, we have now rectified this issue.
